# Generated by Django 3.0.4 on 2020-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='date published'),
        ),
    ]
