# Generated by Django 3.0.4 on 2020-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200319_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
